### PR TITLE
options argument

### LINKED ISSUE #9: invalid argument dupplied foreach
the [``cache_dir``](https://github.com/Incenteev/IncenteevTranslationCheckerBundle/blob/master/DependencyInjection/Compiler/ConfigureTranslatorPass.php#L29) is added to the ``$loaderIds`` rather than the ``$options`` argument of the translator [constructor](https://github.com/symfony/framework-bundle/blob/86119a17ed2547afa0dc0286631c98338e3dc3a3/Translation/Translator.php#L57) and thereby crashes the initialize function of the translator.

### PR DESCRIPTION
**Pull request by wickedOne**
fixes #9

### CODE REVIEW

**Comment by wickedOne** [comment]
apparently this is an issue related to symfony 3.3
same thing happened at the [BazingaJsTranslationBundle](https://github.com/willdurand/BazingaJsTranslationBundle/pull/201)

**Comment by stof** [comment]
closing in favor of #10. Your PR breaks support for all versions before Symfony 3.3

**Comment by xabbuh** [comment]
@stof I think you meant #11 instead. :)

**Comment by stof** [comment]
@xabbuh indeed

**Pull request closed without merging**
